# Salesforce credentials
SF_USERNAME = "bchen@envoy.com"
SF_PASSWORD = "TasksandEvents1"
SF_SECURITY_TOKEN = "nQWlT8vNdnJwxwtfpS1ic4Z7O"

# Google Sheets service account file path
GSPREAD = "/Users/bchen/Downloads/gspread-428120-06947c66447d.json"

# Google Sheets service account info
[gcp_service_account]
type = "service_account"
project_id = "gspread-428120"
private_key_id = "06947c66447dc788a327f0aa14586dc2d0c1c629"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDT5NvOVvIG5Vlu
2oM/iq7W83cr5oICpC+VGWksBroNUfz6nTKD/5tIZOyw0SKvhHiCUTzXvDhRT+WV
5Ns0RbyeSB6C/LgGaXHVkT0QieTcN7a5fu2HJy1Gajd/nDN2rFbt7FD165GOXBv3
tEYDZPw88XaebIBhaGgtriB7Rsg5IbmNKOv2E1GZ1yM4jDS4f1Ey/Ad38vH2Jc3s
fyZFIFj4Kz3viwKoYC+90yYFqG54I5COUZrL0VgURTBjshjrHoPJiK5S3m0TFt6I
781b5LhDoG/A6+n4Dant8rHSoL+KzdUY0KL4KHMISe9qoCb7U4BKgGnP8lv6++gu
13wX5mZ1AgMBAAECggEAWPM4QKDoHfP2fJ4XPbvilJKE4vVze1dgMCeIKnaycLgL
ykrmM1pAXf4cDEfm1yZ1jkM7FtdJDv1KxAdb69Agk5Nz14nuWKa4Ji6/oys32yg6
ORlq7fMIwwgAvz2brwQ+w8cR34JhypCpHu1a/L7OUmkM4glrRTjWjuKLeSSoFa7q
gjBR5WD4ALRKurqLJmFXnFIGyshqRToAONhpGLY5zPQX+2PYPWRE7wngxscps6n0
UKb04FqA7zwnsaffyboM3Z5CYJXPIG3PIP1eYRWcpwNxXLFMi5uAv4MM/7HrzgjS
T8y+eZyEFLm9183I2nd4+m8X84dT4IvDnsuPgwcZGwKBgQDu1vo7SohyAxQmdJx/
GOJqHSMv/xeloe0WyAncqhkhTldFCVzDQpWDXaVgGU/f1X+izREKo6gSHlQKP/EL
5n25Wfd7EhOwNWe0BKQHgLKkbY15BdHxwXppwZUab8Vu0QqQGUxD6FRO5t2cN/0X
Cx2zcrRuDhjHvF3lj2Y/Pq5RFwKBgQDjHkM8NrLGcwW1/pbSmvEXcDQy951isVYO
H8uGJOG41iUfnkRcORIhLSVsZq6US2OBHs8NqZtiihbYUnE7Oz3nTusyC3xBd600
8MMXC2a6j5wMlTa9MiGrCLlRN8/EgFgHTbLnceCtmBIcRf/5JJTZQJdfdhf8OzvE
4KuLvehEUwKBgDAM/iDpmNPfPLGT6lxDpGGW5Rpl5tsC3dEkg59qdU3XFgWkoY4D
GlNohrnzvbcZm+kj+pa6YDjs8xlwzc0IHSkqKXkQJPfhdrCn8lw0Dzy3cav0eM17
kGYwdQ/xhrYJxmdBP6+10ShimBkyxm9ZZCtTG2u82E1u3zEtDXQR5z4XAoGBANS4
FXUiLhNcy+6Hgy/CWyj+uIU8EjbLrbQQ54i+poN+Xsrca16NPYPBSxnamozeh1X6
SyeawaRrfbYikVdOx04MRpFa3Ihc1OeO0MqWrSLzOs82Oky91Xbh9uAxC/IZ21kL
1xKbQDqXAe9lSLhLIPbSXnTUoOZnfDWL0GBUAGVtAoGAbYlG/wnH3yp8RDoSTtPu
qXIf0MnkWflVK/cCKM6mEv4IS/B2hek6g3OSaRIFDJ9TwxFBEpRrC4rquuGfFcbO
QfIY/1i1mRykp2v5TLet11lNdS6zqObVL3NjyfN/Fk5r/UaowocNdycbyJgr6NKh
w37iACxfWI3Pj4yldPPHkZk=
-----END PRIVATE KEY-----"""
client_email = "gspread@gspread-428120.iam.gserviceaccount.com"
client_id = "107253543411792420914"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gspread%40gspread-428120.iam.gserviceaccount.com"
universe_domain = "googleapis.com"